name: healthy_sync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI Packages
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
 # shimmer: ^3.0.0
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  gap: ^3.0.1

  # Firebase Packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # State Management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  # Dependency Injection
  get_it: ^8.0.3

  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^9.1.9
  pretty_dio_logger: ^1.3.1

  # JSON Handling
  #json_serializable: ^6.7.1
  #json_annotation: ^4.8.1
  #freezed: ^3.0.4
  #freezed_annotation: ^3.0.0

  # Localization
 # intl: ^0.19.0
  easy_localization: ^3.0.7+1
  flutter_localizations:
    sdk: flutter

  # Storage
  shared_preferences: ^2.2.3
#  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1

  # Utilities
  image_picker: ^1.1.2
 # flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.14.3
 # build_runner: ^2.4.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
