// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAWh_nboYmneW_8R-S-VPjUwTX33VvGI',
    appId: '1:934002144822:web:f13406a23ba711d6caca97',
    messagingSenderId: '934002144822',
    projectId: 'health-sync-1053e',
    authDomain: 'health-sync-1053e.firebaseapp.com',
    storageBucket: 'health-sync-1053e.firebasestorage.app',
    measurementId: 'G-MBPD24YKWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMw8nT45eZOYCo-LcsUydh4Erqxd6j94',
    appId: '1:934002144822:android:2a90e2941b5e48a5caca97',
    messagingSenderId: '934002144822',
    projectId: 'health-sync-1053e',
    storageBucket: 'health-sync-1053e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyi0lKrV4GURFhLPhA12JXLF9byPeh2A',
    appId: '1:934002144822:ios:c8df7f3a41189d38caca97',
    messagingSenderId: '934002144822',
    projectId: 'health-sync-1053e',
    storageBucket: 'health-sync-1053e.firebasestorage.app',
    iosBundleId: 'com.HealthySync.healthySync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyi0lKrV4GURFhLPhA12JXLF9byPeh2A',
    appId: '1:934002144822:ios:c8df7f3a41189d38caca97',
    messagingSenderId: '934002144822',
    projectId: 'health-sync-1053e',
    storageBucket: 'health-sync-1053e.firebasestorage.app',
    iosBundleId: 'com.HealthySync.healthySync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQAWh_nboYmneW_8R-S-VPjUwTX33VvGI',
    appId: '1:934002144822:web:8f4ec5a870b7a458caca97',
    messagingSenderId: '934002144822',
    projectId: 'health-sync-1053e',
    authDomain: 'health-sync-1053e.firebaseapp.com',
    storageBucket: 'health-sync-1053e.firebasestorage.app',
    measurementId: 'G-V6KD7M5B1G',
  );
}
